# apiVersion: v1
# data:
#   config.yaml: |-
#     "resourceRules":
#       "cpu":
#         "containerLabel": "container"
#         "containerQuery": |
#           sum by (<<.GroupBy>>) (
#             irate (
#                 container_cpu_usage_seconds_total{<<.LabelMatchers>>,container!="",pod!=""}[120s]
#             )
#           )
#         "nodeQuery": |
#           sum by (<<.GroupBy>>) (
#             1 - irate(
#               node_cpu_seconds_total{mode="idle"}[60s]
#             )
#             * on(namespace, pod) group_left(node) (
#               node_namespace_pod:kube_pod_info:{<<.LabelMatchers>>}
#             )
#           )
#           or sum by (<<.GroupBy>>) (
#             1 - irate(
#               windows_cpu_time_total{mode="idle", job="windows-exporter",<<.LabelMatchers>>}[4m]
#             )
#           )
#         "resources":
#           "overrides":
#             "namespace":
#               "resource": "namespace"
#             "node":
#               "resource": "node"
#             "pod":
#               "resource": "pod"
#       "memory":
#         "containerLabel": "container"
#         "containerQuery": |
#           sum by (<<.GroupBy>>) (
#             container_memory_working_set_bytes{<<.LabelMatchers>>,container!="",pod!=""}
#           )
#         "nodeQuery": |
#           sum by (<<.GroupBy>>) (
#             node_memory_MemTotal_bytes{job="node-exporter",<<.LabelMatchers>>}
#             -
#             node_memory_MemAvailable_bytes{job="node-exporter",<<.LabelMatchers>>}
#           )
#           or sum by (<<.GroupBy>>) (
#             windows_cs_physical_memory_bytes{job="windows-exporter",<<.LabelMatchers>>}
#             -
#             windows_memory_available_bytes{job="windows-exporter",<<.LabelMatchers>>}
#           )
#         "resources":
#           "overrides":
#             "instance":
#               "resource": "node"
#             "namespace":
#               "resource": "namespace"
#             "pod":
#               "resource": "pod"
#       "window": "5m"
# kind: ConfigMap
# metadata:
#   labels:
#     app.kubernetes.io/component: metrics-adapter
#     app.kubernetes.io/name: prometheus-adapter
#     app.kubernetes.io/part-of: kube-prometheus
#     app.kubernetes.io/version: 0.9.1
#   name: adapter-config
#   namespace: monitoring

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
  labels:
    app: prometheus-adapter
data:
  config.yaml: |
    rules:
    - seriesQuery: 'random_number_total{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod: 
            resource: pod
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
    resourceRules:
      cpu:
        containerQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, container_label_io_kubernetes_container_name!=""}[3m])) by (<<.GroupBy>>)
        nodeQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, id='/'}[3m])) by (<<.GroupBy>>) by (<<.GroupBy>>)
        resources:
          overrides:
            container_label_io_kubernetes_pod_namespace:
              resource: namespace
            node:
              resource: node
            container_label_io_kubernetes_pod_name:
              resource: pod
        containerLabel: container_label_io_kubernetes_container_name
      memory:
        containerQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>, container_label_io_kubernetes_container_name!=""}) by (<<.GroupBy>>)
        nodeQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>,id='/'}) by (<<.GroupBy>>)
        resources:
          overrides:
            container_label_io_kubernetes_pod_namespace:
              resource: namespace
            node:
              resource: node
            container_label_io_kubernetes_pod_name:
              resource: pod
        containerLabel: container_label_io_kubernetes_container_name
      window: 3m